### PR TITLE
fix: reset profile bio from latest data

### LINKED ISSUE #513: bug: Bio resets visually after save
When editing bio and then saving, the bio text field reverts state to the previous one and not the new updated one.

Probably caused by profile.data getting reset without getting new data beforehand

### PR DESCRIPTION
**Pull request by rexxDigital**
Fixes #513

Not sure if refetching is the preferred approach here, happy to change it if you’d rather handle this differently.

Edit:
We can just not reset from stale data of course

### CODE REVIEW

File: packages/client/components/app/interface/settings/user/profile/UserProfileEditor.tsx [hunk 1]
```diff
@@ -135,12 +130,14 @@ export function UserProfileEditor(props: Props) {
...
+    await profile.refetch();
+    onReset();
   }
 
-  const submit = Form2.useSubmitHandler(editGroup, onSubmit, onReset);
+  const submit = Form2.useSubmitHandler(editGroup, onSubmit);
 
   return (
-    <form onSubmit={submit}>
+    <form onSubmit={submit} onReset={onReset}>
```
Comment (insertish) [inline packages/client/components/app/interface/settings/user/profile/UserProfileEditor.tsx]: I don't believe this does anything

File: packages/client/components/app/interface/settings/user/profile/UserProfileEditor.tsx [hunk 2]
```diff
@@ -135,12 +130,14 @@ export function UserProfileEditor(props: Props) {
     }
 
     await props.user.edit(changes);
+    await profile.refetch();
+    onReset();
```
Comment (insertish) [inline packages/client/components/app/interface/settings/user/profile/UserProfileEditor.tsx]: onReset is already called by the submit handler after this function body exits

File: packages/client/components/app/interface/settings/user/profile/UserProfileEditor.tsx [hunk 3]
```diff
@@ -135,12 +130,14 @@ export function UserProfileEditor(props: Props) {
     }
 
     await props.user.edit(changes);
+    await profile.refetch();
```
Comment (insertish) [inline packages/client/components/app/interface/settings/user/profile/UserProfileEditor.tsx]: We should instead just update the queryClient's value of the profile.

**Comment by insertish** [comment]
Refactored onReset back in to make this a little bit cleaner, see 18bd7d0f74839cec55973ccaff8ec3753dac8384.

Thanks for the contribution!
