### PR TITLE
fix: Bypass email registration page if the server configuration has email disabled

### LINKED ISSUE #759: Email verification page is shown after account creation regardless of server configuration
### What happened?

Email verification page is shown after account creation regardless of whether the server has email verification enabled. There is a // TODO regarding it. The web app would have to fetch the server's config and skip the email verification step of the flow if email is disabled.

### PR DESCRIPTION
**Pull request by Dadadah**
After registration, the verify email page is shown regardless of whether email is enabled or not. This PR makes the account creation flow skip email verification and log straight in if the server is configured with email disabled.

Requires https://github.com/stoatchat/javascript-client-sdk/pull/127 due to the configuration currently not being loaded automatically by the javascript client sdk.

Resolves #759

Tested by @alice_werefox and @dadadah

### CODE REVIEW

**Comment by Bob-Swan** [comment]
I tested an alternative approach that avoids relying on client SDK config preload timing: after /auth/account/create, fetch GET / and branch on eatures.email directly in FlowCreate.\n\nOpened here for comparison: https://github.com/stoatchat/for-web/pull/853\n\nHappy to close if you'd rather keep everything in this PR and I can adapt it there instead.

File: packages/client/components/auth/src/flows/FlowCreate.tsx [hunk 1]
```diff
@@ -34,13 +37,19 @@ export default function FlowCreate() {
...
+    } else {
+      await login(
+        {
+          email,
+          password,
+        },
+        modals,
+      );
+      navigate("/login/auth", { replace: true });
+    }
```
Comment (insertish) [inline packages/client/components/auth/src/flows/FlowCreate.tsx]: I think, in case there is an issue with loading configuration (really this should be rebuilt and made 100% reliable), I'd prefer if we show the email flow if (configuration is not present) OR (email is enabled).

**Review by insertish — DISMISSED** [review]

File: packages/client/components/auth/src/flows/FlowCreate.tsx (hunk 1 above)
Comment (Dadadah) [reply packages/client/components/auth/src/flows/FlowCreate.tsx]: Good catch, I've reversed that statement and added a configuration presence check.

**Review by chrishultin — APPROVED** [review]

**Review by gabrielfordevelopment — APPROVED** [review]
